# Generated by Django 2.0.3 on 2018-06-08 20:33

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='colour',
            field=models.CharField(default='#D3D3D3', max_length=7),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=profiles.models.upload_location),
        ),
    ]
