# Generated by Django 2.0.3 on 2018-06-08 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20180608_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bank',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
