# Generated by Django 2.0.3 on 2018-06-13 16:16

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20180612_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='colour',
            field=colorfield.fields.ColorField(default='D3D3D3', max_length=18),
        ),
    ]
