# Generated by Django 2.0.3 on 2018-06-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20180613_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='colour',
            field=models.CharField(default='D3D3D3', max_length=7),
        ),
    ]
