# Generated by Django 2.0.3 on 2018-06-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20180615_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bank',
            new_name='withdrawable_bank',
        ),
        migrations.AddField(
            model_name='profile',
            name='non_withdrawable_bank',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
