# Generated by Django 2.0.3 on 2018-06-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20180622_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ranking',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
