# Generated by Django 2.0.3 on 2018-06-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_profile_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ranking',
            field=models.IntegerField(default=0),
        ),
    ]
