# Generated by Django 2.0.3 on 2018-06-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20180625_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_number_users',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ranking',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
