# Generated by Django 2.0.3 on 2018-06-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20180625_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ranking',
            field=models.IntegerField(default=0),
        ),
    ]
