# Generated by Django 2.0.3 on 2018-08-17 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        ('profiles', '0011_auto_20180625_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdrawable_bank', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('non_withdrawable_bank', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('ranking', models.IntegerField(default=0)),
                ('group', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='wallets_group', to='community.CommunityGroup')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='non_withdrawable_bank',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ranking',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='total_number_users',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='withdrawable_bank',
        ),
        migrations.AddField(
            model_name='wallet',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallets_profile', to='profiles.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='groups',
            field=models.ManyToManyField(through='profiles.Wallet', to='community.CommunityGroup'),
        ),
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together={('profile', 'group')},
        ),
    ]
