# Generated by Django 2.0.3 on 2018-08-21 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20180821_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityinvite',
            name='inviter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='community_invites_inviter', to='profiles.Profile'),
        ),
    ]
