# Generated by Django 2.0.3 on 2018-08-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_communityinvite_inviter'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
