# Generated by Django 2.0.3 on 2018-08-29 17:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_wallet_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityinvite',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 29, 17, 13, 12, 758070, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='communityinvite',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 29, 17, 13, 21, 876986, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='communityinvite',
            name='status',
            field=models.CharField(choices=[('sent', 'Active'), ('declined', 'Deactivated'), ('declined_blocked', 'Declined and Blocked'), ('accepted', 'Accepted')], default='sent', max_length=30),
        ),
        migrations.AddField(
            model_name='wallet',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 29, 17, 13, 30, 573534, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallet',
            name='founder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wallet',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 29, 17, 13, 34, 402160, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallet',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('deactivated', 'Deactivated')], default='active', max_length=30),
        ),
    ]
