# Generated by Django 2.0.3 on 2018-08-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitygroup',
            name='removable',
            field=models.BooleanField(default=True),
        ),
    ]
