# Generated by Django 2.0.3 on 2018-08-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_communitygroup_removable'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitygroup',
            name='header_background_colour',
            field=models.CharField(default='ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='communitygroup',
            name='header_text_colour',
            field=models.CharField(default='000000', max_length=7),
        ),
        migrations.AddField(
            model_name='communitygroup',
            name='max_number_users',
            field=models.IntegerField(default=32),
        ),
        migrations.AddField(
            model_name='communitygroup',
            name='members_can_inv',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='communitygroup',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('deactivated', 'Deactivated')], default='active', max_length=30),
        ),
    ]
