# Generated by Django 2.0.3 on 2018-05-26 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_a', models.CharField(max_length=200)),
                ('team_b', models.CharField(max_length=200)),
                ('game_date', models.DateTimeField(verbose_name='Game start date')),
                ('expected_duration', models.DurationField(default=datetime.timedelta(0, 120))),
                ('status', models.CharField(choices=[('not_begun', 'Not begun'), ('starting', 'Starting'), ('ongoing', 'Ongoing'), ('finished_not_confirmed', 'Finished - Not yet confirmed'), ('finished_confirmed', 'Finished - Confirmed')], default='not_begun', max_length=30)),
            ],
        ),
    ]
