# Generated by Django 2.0.3 on 2018-05-27 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userbetting', '0002_auto_20180527_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='team_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_team_a', to='userbetting.Team'),
        ),
        migrations.AlterField(
            model_name='game',
            name='team_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_team_b', to='userbetting.Team'),
        ),
    ]
