# Generated by Django 2.0.3 on 2018-05-29 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userbetting', '0003_auto_20180527_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bet',
            old_name='Amount',
            new_name='amount',
        ),
    ]
