# Generated by Django 2.0.3 on 2018-06-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbetting', '0004_auto_20180529_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='twitch_url',
            field=models.URLField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='game',
            name='videogame',
            field=models.CharField(choices=[('CSGO', 'cs:go'), ('SC2', 'starcraft'), ('LOL', 'League of Legends'), ('Dota', 'Dota 2')], default='cs:go', max_length=30),
        ),
        migrations.AddField(
            model_name='game',
            name='winning_team',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='colour',
            field=models.CharField(default='#D3D3D3', max_length=7),
        ),
        migrations.AddField(
            model_name='team',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='teamLogos'),
        ),
    ]
