# Generated by Django 2.0.3 on 2018-06-12 21:20

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userbetting', '0005_auto_20180611_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='colour',
            field=colorfield.fields.ColorField(default='#D3D3D3', max_length=18),
        ),
    ]
