# Generated by Django 2.0.3 on 2018-06-13 16:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userbetting', '0006_auto_20180612_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 13, 16, 16, 9, 242592, tzinfo=utc), editable=False),
        ),
        migrations.AddField(
            model_name='bet',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 13, 16, 16, 9, 242592, tzinfo=utc)),
        ),
    ]
