# Generated by Django 2.0.3 on 2018-06-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbetting', '0008_auto_20180613_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='twitch_url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='winning_team',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
