# Generated by Django 2.0.3 on 2018-06-15 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userbetting', '0009_auto_20180615_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='created',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='modified',
        ),
    ]
