# Generated by Django 2.0.3 on 2018-06-15 13:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userbetting', '0010_auto_20180615_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 15, 13, 26, 45, 974316, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bet',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 15, 13, 26, 52, 897957, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
