# Generated by Django 2.0.3 on 2018-06-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbetting', '0014_auto_20180620_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Lost', 'Lost'), ('Paid', 'Paid')], default='Open', max_length=30),
        ),
    ]
