# Generated by Django 2.0.3 on 2018-06-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbetting', '0015_bet_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('Not begun', 'Not begun'), ('Starting', 'Starting'), ('Ongoing', 'Ongoing'), ('Finished - Not yet confirmed', 'Finished - Not yet confirmed'), ('Finished - Confirmed', 'Finished - Confirmed'), ('Finished - All bets paid', 'Finished - All bets paid')], default='Not begun', max_length=30),
        ),
    ]
