# Generated by Django 2.0.3 on 2018-06-20 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userbetting', '0016_auto_20180620_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='winning_team',
            field=models.CharField(blank=True, choices=[('Not Decided', 'Not Decided'), (models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_team_a', to='userbetting.Team'), None), (models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_team_b', to='userbetting.Team'), None)], default='Not Decided', max_length=60, null=True),
        ),
    ]
