# Generated by Django 2.0.3 on 2018-06-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbetting', '0018_auto_20180620_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='game',
            name='winning_team',
            field=models.CharField(blank=True, choices=[('Not Decided', 'Not Decided'), ('Team A is the winner', 'Team A is the winner'), ('Team B is the winner', 'Team B is the winner')], default='Not Decided', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='colour',
            field=models.CharField(default='D3D3D3', max_length=7),
        ),
    ]
