# Generated by Django 2.0.3 on 2018-06-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbetting', '0019_auto_20180622_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='videogame',
            field=models.CharField(choices=[('CSGO', 'cs:go'), ('SC2', 'starcraft'), ('LOL', 'League of Legends'), ('Dota', 'Dota 2'), ('Overwatch', 'Overwatch')], default='cs:go', max_length=30),
        ),
    ]
