# Generated by Django 2.0.3 on 2018-06-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbetting', '0020_auto_20180623_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='winnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
