# Generated by Django 2.0.3 on 2018-06-28 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userbetting', '0021_bet_winnings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('tournament_id', models.AutoField(primary_key=True, serialize=False)),
                ('tournament_name', models.CharField(max_length=120, unique=True)),
                ('videogame', models.CharField(choices=[('CSGO', 'cs:go'), ('SC2', 'starcraft'), ('LOL', 'League of Legends'), ('Dota', 'Dota 2'), ('Overwatch', 'Overwatch')], default='cs:go', max_length=30)),
                ('tournament_start_date', models.DateTimeField(verbose_name='Tournament start date')),
                ('tournament_send_date', models.DateTimeField(verbose_name='Tournament end date')),
                ('main_twitch_url', models.URLField(blank=True, null=True, unique=True)),
                ('status', models.CharField(choices=[('Not begun', 'Not begun'), ('Ongoing', 'Ongoing'), ('Finished', 'Finished')], default='Not begun', max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='videogame',
            field=models.CharField(blank=True, choices=[('CSGO', 'cs:go'), ('SC2', 'starcraft'), ('LOL', 'League of Legends'), ('Dota', 'Dota 2'), ('Overwatch', 'Overwatch')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='userbetting.Tournament'),
        ),
    ]
