# Generated by Django 2.0.3 on 2018-07-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbetting', '0023_auto_20180702_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='api_match_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='game',
            name='api_modified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='api_modified_at'),
        ),
        migrations.AddField(
            model_name='team',
            name='api_team_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='team',
            name='picture_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='api_modified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='api_modified_at'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='api_tournament_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_name',
            field=models.CharField(max_length=120),
        ),
    ]
