# Generated by Django 2.0.3 on 2018-07-03 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userbetting', '0024_auto_20180703_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='tournament_send_date',
            new_name='tournament_end_date',
        ),
    ]
