# Generated by Django 2.0.3 on 2018-07-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbetting', '0025_auto_20180703_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='videogame',
            field=models.CharField(blank=True, choices=[('CSGO', 'cs:go'), ('SC2', 'starcraft'), ('LoL', 'League of Legends'), ('Dota', 'Dota 2'), ('Overwatch', 'Overwatch')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='videogame',
            field=models.CharField(choices=[('CSGO', 'cs:go'), ('SC2', 'starcraft'), ('LoL', 'League of Legends'), ('Dota', 'Dota 2'), ('Overwatch', 'Overwatch')], default='cs:go', max_length=30),
        ),
    ]
