# Generated by Django 2.0.3 on 2018-07-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbetting', '0026_auto_20180704_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='api_series_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
