# Generated by Django 2.0.3 on 2018-07-16 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userbetting', '0028_auto_20180716_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stage_games', to='userbetting.Stage'),
        ),
        migrations.AddField(
            model_name='stage',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tournament_stages', to='userbetting.Tournament'),
        ),
    ]
