# Generated by Django 2.0.3 on 2018-07-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbetting', '0029_auto_20180716_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='stage_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tournament end date'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tournament end date'),
        ),
    ]
