# Generated by Django 2.0.3 on 2018-08-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbetting', '0030_auto_20180724_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videogame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videogame_name', models.CharField(choices=[('CSGO', 'cs:go'), ('SC2', 'starcraft'), ('LoL', 'League of Legends'), ('Dota', 'Dota 2'), ('Overwatch', 'Overwatch')], default='LoL', max_length=30)),
                ('api_videogame_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='teamLogos')),
                ('colour', models.CharField(default='D3D3D3', max_length=7)),
                ('alt_colour', models.CharField(default='D3D3D3', max_length=7)),
            ],
        ),
    ]
