# Generated by Django 2.0.3 on 2018-08-01 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userbetting', '0031_videogame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='videogame',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='videogame_tournaments', to='userbetting.Videogame'),
        ),
    ]
