# Generated by Django 2.0.3 on 2018-08-01 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userbetting', '0032_auto_20180801_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='videogame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='videogame_games', to='userbetting.Videogame'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='videogame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='videogame_tournaments', to='userbetting.Videogame'),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='videogame_name',
            field=models.CharField(choices=[('csgo', 'cs:go'), ('sc2', 'starcraft'), ('lol', 'League of Legends'), ('dota', 'Dota 2'), ('overwatch', 'Overwatch')], default='LoL', max_length=30, unique=True),
        ),
    ]
