# Generated by Django 2.0.3 on 2018-08-17 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        ('userbetting', '0033_auto_20180801_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='BettingGameGroup',
            fields=[
                ('Betting_group_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='tournament',
            name='groups',
            field=models.ManyToManyField(to='community.CommunityGroup'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_bets', to='userbetting.BettingGameGroup'),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('Starting', 'Starting'), ('running', 'Running'), ('finished', 'Finished'), ('Finished - Not yet confirmed', 'Finished - Not yet confirmed'), ('Finished - Confirmed', 'Finished - Confirmed'), ('Finished - All bets paid', 'Finished - All bets paid')], default='not_started', max_length=30),
        ),
        migrations.AddField(
            model_name='bettinggamegroup',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_bgg', to='userbetting.Game'),
        ),
        migrations.AddField(
            model_name='bettinggamegroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_bgg', to='community.CommunityGroup'),
        ),
        migrations.AlterUniqueTogether(
            name='bettinggamegroup',
            unique_together={('game', 'group')},
        ),
    ]
