# Generated by Django 2.0.3 on 2018-08-17 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userbetting', '0034_auto_20180817_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bet',
            old_name='game',
            new_name='betting_group',
        ),
    ]
