# Generated by Django 2.0.3 on 2018-08-21 17:21

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('userbetting', '0035_auto_20180817_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bettinggamegroup',
            old_name='Betting_group_id',
            new_name='betting_group_id',
        ),
    ]
