# Generated by Django 2.0.3 on 2018-08-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbetting', '0037_auto_20180825_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='bettinggamegroup',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('deactivated', 'Deactivated')], default='active', max_length=30),
        ),
    ]
